// Industry image library — used to auto-fill template photo slots when the
// business has not uploaded their own. The actual library data lives in
// industryLibrary.generated.js, which is auto-generated by
// `pnpm --filter @workspace/scripts run gen-restaurant-assets` from the
// on-disk manifest.json so the two stay in sync.

import { RESTAURANT_LIBRARY } from "./industryLibrary.generated.js";

const RESTAURANT_INDUSTRIES = new Set([
  "Restaurant", "Pizza Restaurant", "Mexican Restaurant", "Chinese Restaurant",
  "Breakfast and Cafe", "Bar and Grill", "Italian Restaurant", "Bakery",
]);

function libraryFor(industry) {
  if (RESTAURANT_INDUSTRIES.has(industry)) return RESTAURANT_LIBRARY;
  return [];
}

// Stable string hash (djb2-ish, 32-bit).
function hash(str) {
  let h = 5381;
  for (let i = 0; i < str.length; i++) h = ((h << 5) + h + str.charCodeAt(i)) | 0;
  return Math.abs(h);
}

// Pick a deterministic fallback photo from the industry library.
// Same (industry, businessName, tag, slot) always returns the same URL,
// and different slots return distinct images when the pool is large enough.
export function pickFallbackPhoto(industry, businessName, tag = "hero", slot = 0) {
  const lib = libraryFor(industry);
  let pool = lib.filter(i => i.tag === tag);
  if (pool.length === 0) pool = lib;
  if (pool.length === 0) return null;
  const seed = `${businessName || "default"}|${slot}`;
  const startIdx = hash(seed) % pool.length;
  const idx = (startIdx + slot) % pool.length;
  return pool[idx].url;
}

// Resolve a photo array against the library — replaces empty slots with
// deterministic fallbacks. Always returns an array of length `count` of URLs.
export function resolvePhotos(industry, businessName, photos = [], count = 3) {
  const out = [];
  const tags = ["hero", "food-detail", "interior"];
  for (let i = 0; i < count; i++) {
    const supplied = photos[i];
    if (supplied) { out.push(supplied); continue; }
    const tag = tags[i] || "hero";
    out.push(pickFallbackPhoto(industry, businessName, tag, i));
  }
  return out;
}

export function hasIndustryLibrary(industry) {
  return libraryFor(industry).length > 0;
}
