import { Router, type IRouter } from "express";
import healthRouter from "./health";
import campaignsRouter from "./campaigns";
import spotsRouter from "./spots";
import checkoutRouter from "./checkout";
import adminRouter from "./admin";
import adminCampaignsRouter from "./adminCampaigns";
import adminOutreachRouter from "./adminOutreach";
import adAssistantRouter from "./adAssistant";
import adGeneratorV2Router from "./adGeneratorV2";
import adGeneratorV3Router from "./adGeneratorV3";
import adGeneratorV4Router from "./adGeneratorV4";
import aiUpgradeRouter from "./aiUpgrade";
import aiEnhanceRouter from "./aiEnhance";
import adGeneratorV5Router from "./adGeneratorV5";
import adGeneratorV6Router from "./adGeneratorV6";
import adStudioRouter from "./adStudio";
import aiModelTestRouter from "./aiModelTest";
import imageLibraryRouter from "./imageLibrary";
import dealersRouter from "./dealers";
import adGenV7Router from "./adGenV7";
import aiAdCreatorRouter from "./aiAdCreator";
import adGenGrokRouter from "./adGenGrok";
import interestRouter from "./interest";
import subscriptionsRouter from "./subscriptions";

const router: IRouter = Router();

router.use(healthRouter);
router.use(campaignsRouter);
router.use(spotsRouter);
router.use(checkoutRouter);
router.use(adminRouter);
router.use(adminCampaignsRouter);
router.use(adminOutreachRouter);
router.use(adAssistantRouter);
router.use(adGeneratorV2Router);
router.use(adGeneratorV3Router);
router.use(adGeneratorV4Router);
router.use(aiUpgradeRouter);
router.use(aiEnhanceRouter);
router.use(adGeneratorV5Router);
router.use(adGeneratorV6Router);
router.use(adStudioRouter);
router.use(aiModelTestRouter);
router.use(imageLibraryRouter);
router.use(dealersRouter);
router.use(adGenV7Router);
router.use(aiAdCreatorRouter);
router.use(adGenGrokRouter);
router.use(interestRouter);
router.use(subscriptionsRouter);

export default router;
